# Main configuration file for ${project.name} v${project.version}

# localized language support
language: en-US

# If this list is empty, all worlds will be added to the enabled worlds list
enabled-worlds:
#  - enabled_world1
#  - enabled_world2

# These worlds will be removed from the enabled worlds list
disabled-worlds:
  - disabled_world1
  - disabled_world2

# RoadBlock tool material - customize name and lore in messages file
tool-material: GOLDEN_PICKAXE

# Highlight material for protected blocks
protect-material: EMERALD_BLOCK

# Highlight material for unprotected blocks
unprotect-material: REDSTONE_BLOCK

# Display total blocks in status
display-total: true

# How far to search for adjacent road blocks from clicked location
spread-distance: 100

# How far to search for road blocks with show command
show-distance: 100

# Distance above roads to prevent block placement
no-place-height: 3

# Prevent mobs from targeting players farther than this distance when on roads
target-distance: 5

# Distance in blocks a player can be above a road block, and still be considered 'on road' for mob targeting
on-road-height: 6

# Prevent snow forming above road blocks
snow-plow: true

# Enable sound effects
sound-effects: true

# materials to be considered road blocks (material types documented here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html)
materials:
  - GRASS_PATH
  - COBBLESTONE
  - COBBLESTONE_SLAB
  - COBBLESTONE_STAIRS
  - MOSSY_COBBLESTONE
  - MOSSY_COBBLESTONE_SLAB
  - MOSSY_COBBLESTONE_STAIRS
  - STONE_BRICKS
  - STONE_BRICK_SLAB
  - STONE_BRICK_STAIRS
  - CRACKED_STONE_BRICKS
  - MOSSY_STONE_BRICKS
  - MOSSY_STONE_BRICK_SLAB
  - MOSSY_STONE_BRICK_STAIRS
